spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    security:
      protocol: SASL_SSL
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CONFLUENT_API_KEY}" password="${CONFLUENT_API_SECRET}";
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${CONFLUENT_SR_API_KEY}:${CONFLUENT_SR_API_SECRET}
    producer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CONFLUENT_API_KEY}" password="${CONFLUENT_API_SECRET}";
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: ${CONFLUENT_SR_API_KEY}:${CONFLUENT_SR_API_SECRET}

app:
  kafka:
    retry:
      attempts: 5
      backoff: 2000

logging:
  level:
    org.springframework.kafka: INFO
    springkafka: INFO
    root: WARN