spring:
  application:
    name: weather-producer-consumer
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: weather-app-avro
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      auto-offset-reset: latest
      properties:
        spring.json.value.default.type: springkafka.WeatherReading
        spring.json.trusted.packages: "*"
